config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { applications: 'applications' }, controllers: {registrations: 'registrations'}
  root to: 'tamplates#index'

  resources :tamplates


  devise_scope :user do
    get "login", :to => "devise/sessions#new"
    get "register", :to => "devise/registrations#new"
    get "settings", :to => "devise/registrations#edit"
    get "logout",   :to => "devise/sessions#destroy"
    get 'sign_in', :to => 'devise/sessions#new'
 end

  #devise_for :users do
    #get '/users/sign_out' => 'devise/sessions#destroy'
  #end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tamplate.rb
class Tamplate < ApplicationRecord
  validates :templ_type, presence: true, length: { minimum: 1 }
  validates :koef,presence: true, length: { minimum: 1 }
  validates :name,presence: true, length: { minimum: 2 }
  validates :chernovik,presence: true, length: { minimum: 2 }
  validates :opisanie,presence: true, length: { minimum: 2 }
  

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def create

  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
    redirect_to 'tamplates/show.html.erb'
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def after_sign_up_path_for(recource)
    root_path
  end
end

app/controllers/tamplates_controller.rb
class TamplatesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_tamplate, only: %i[update show destroy edit]


  def create

    tamplate = Tamplate.create(tamplate_params)
    if tamplate.save
      redirect_to tamplates_path
    else

  end
  end

  def update
    @tamplate.update(tamplate_params)

    redirect_to tamplates_path
  end

  def destroy
    @tamplate.destroy

    redirect_to tamplates_path
  end

  def show
    @tamplates = Tamplate.all
  end

  def index
    @tamplates = Tamplate.all
  end

  def new
    @tamplate = Tamplate.new
  end

  def edit

  end

  def base
  end



  def after_sign_in_path_for(resource)
    current_user_path
  end


  private

  def tamplate_params
    params.require(:tamplate).permit(:templ_type, :koef, :name, :chernovik, :opisanie)
  end

  def set_tamplate
    @tamplate = Tamplate.find(params[:id])
  end



end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  

  # GET /resource/sign_in
   def new
     super


   end

  # POST /resource/sign_in
   def create
     super


   end

  # DELETE /session/sign_out
   def destroy
     super
   end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tamplate_helper.rb
module TamplateHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mrt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <ul class='navbar navbar-expand-lg bg-light'>
      <div class="container-fluid">
      <% if user_signed_in? %>
        <li class="navbar-nav">
          <%= link_to 'Выход', logout_path, method: :delete, class: 'nav-link' %>
        </li>
          <% else %>
          <li class="navbar-nav">
            <%= link_to 'Вход', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="navbar-nav">
            <%= link_to 'Регистрация', new_user_registration_path, class: 'nav-link' %>
          </li>
      <% end %>
    </ul>

      </div>
    <div class="wrapper">
    <%= yield %>

    </div>
  </body>
</html>

app/views/persons/profile.html.erb
<h1>Persons#profile</h1>
<p>Find me in app/views/persons/profile.html.erb</p>

app/views/tamplates/_form.html.erb
<%= form_with model: @tamplate do |form| %>
<p><%= form.label :templ_type, 'Тип' %></p>
<p><%= form.number_field :templ_type %></p>

<p><%= form.label :koef, 'Коф.' %></p>
<p><%= form.number_field :koef %></p>


<p><%= form.label :name, 'Имя' %></p>
<p><%= form.text_area :name, rows: 2 %></p>

<p class="mb"><%= form.label :chernovik, 'Чероновик' %></p>
<p><%= form.text_area :chernovik, rows: 5, class: 'form-text-area' %></p>

<p><%= form.label :opisanie, 'Описание' %></p>
<p><%= form.text_area :opisanie, rows: 5, class: 'form-text-field' %></p>

app/views/tamplates/base.html.erb
<h2>Страница регистрации и вход в систему</h2>

<form action="/tamplates" method="post">

<p class="mt"><%= link_to "Все шаблоны", "/tamplates" %></p>

</form>

app/views/tamplates/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактирование шаблона<%= @tamplate.id %> </h2>

  <%= form_with model: @tamplate do |form| %>
  <p><%= form.label :templ_type, 'Тип' %></p>
  <p><%= form.number_field :templ_type %></p>

  <p><%= form.label :koef, 'Коф.' %></p>
  <p><%= form.number_field :koef %></p>

  <p><%= form.label :name, 'Имя' %></p>
  <p><%= form.text_area :name, rows: 2 %></p>

  

  <p><%= form.label :opisanie, 'Описание' %></p>
  <p><%= form.text_area :opisanie, rows: 10, class: 'form-text-field' %></p>

  <p class="mt"><%= form.submit 'Сохранить', class: 'button button-main' %></p>

  <p class="mt"><%= link_to "Все шаблоны", "/tamplates" %></p>
  <% end %>
</div>

app/views/tamplates/index.html.erb
<div class="container">
  <h1 class="title-lg mb"></h1>
  <table class="table table-sm table-inverse">

    <div class="container">
      <h1 class="title-lg mb">МРТ шаблон</h1>
      <table class="table table-sm table-inverse">
        <tr>
          <th>id</th>
          <th>Имя</th>
          <th>Тип</th>
          <th>Коэф</th>
          <th>Изменить</th>
          <th>Удалить</th>
        </tr>
        <% @tamplates.each do |tamplate| %>

         <tr>
           <td><%= link_to "#{tamplate.id}",  tamplate_path(tamplate.id) %></td>
           <td><%= link_to "#{tamplate.name}",  tamplate_path(tamplate.id) %></td>
           <td><%= link_to "#{tamplate.templ_type}",  tamplate_path(tamplate.id) %></td>
           <td><%= link_to "#{tamplate.koef}",  tamplate_path(tamplate.id) %></td>
           <td><%= link_to ('Редактировать'),  edit_tamplate_path(tamplate.id), class: 'button button-main' %></td>
           <td><%= button_to ('Удалить'),  tamplate_path(tamplate.id), class: 'button button-main', method: :delete %></td>
         </tr>



         <% end %>
         <p class="mt">
           <%= link_to "Новый шаблон", new_tamplate_path, class: 'button button-main' %>

         </p>
    </div>

</div>

app/views/tamplates/new.html.erb
<div class="container">
  <h2 class="title-lg mb">Новый шаблон</h2>

  <% if @tamplate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tamplate.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% @tamplate.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @tamplate do |form| %>


  <p><%= form.label :templ_type, 'Тип' %></p>
  <p><%= form.number_field :templ_type %></p>

  <p><%= form.label :koef, 'Коф.' %></p>
  <p><%= form.number_field :koef %></p>


  <p><%= form.label :name, 'Имя' %></p>
  <p><%= form.text_area :name, rows: 2 %></p>

  <p class="mb"><%= form.label :chernovik, 'Чероновик' %></p>
  <p><%= form.text_area :chernovik, rows: 5, class: 'form-text-area' %></p>

  <p><%= form.label :opisanie, 'Описание' %></p>
  <p><%= form.text_area :opisanie, rows: 5, class: 'form-text-field' %></p>

  <p class="mb"><%= form.submit 'Создать', class: 'button button-main' %></p>
  <p class="mt"><%= link_to "Все шаблоны", "/tamplates" %></p>
  <% end %>
</div>

app/views/tamplates/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Шаблон <%= @tamplate.id %></h2>


  <table>
     <tr><th>Имя</th><th>Тип</th><th>Коэф</th><th>Описание</th><th>Черновик</th></tr>
     <tr><td><p class="mb-sm"><%= @tamplate.name %></p></td><td><p class="mb-sm"><%= @tamplate.templ_type %></p></td><td><p class="mb-sm"><%= @tamplate.koef %></p></td><td><p class="mb-sm"><%= @tamplate.opisanie %></p></td><td><p class="mb-sm"><%= @tamplate.chernovik %></p></td></tr>
  </table>

  <div class="mt">
    <%= link_to ('Редатировать'), edit_tamplate_path(@tamplate), title: 'Изменить шаблон'%>
    <%= button_to ('Удалить'), tamplate_path(@tamplate), method: :delete, title: 'Удалить шаблон' %>
  </div>

  <p class="mt"><%= link_to "Все шаблоны", "/tamplates" %></p>
</div>

app/views/tamplates/update.html.erb
Ваш запрос обработан